network/urls.py
from django.urls import path

from . import views

app_name = "network"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<str:username>", views.user_posts, name="profile"),
    path("following", views.following_view, name="following"),
    path("add_post", views.add_post, name="add_post"),
    path("like/<int:post_id>", views.like, name="like"),
    path("posts/<str:username>", views.user_posts, name="user_posts"),
    path("follow_user/<str:user_to_follow>", views.follow_user, name="follow_user"),
    path("posts", views.posts, name="posts"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import time



class User(AbstractUser):
    followers = models.ManyToManyField("User", related_name="following_users")
    following = models.ManyToManyField("User", related_name="follower_users")
    liked_posts = models.ManyToManyField("Post", related_name="liked", blank=True, null=True)
    def serialize(self):
        return {
            "username": self.username,
            "noFollowers": self.followers.count(),
            "noFollowing": self.following.count(),
        }



class Post(models.Model):
    author = models.ForeignKey("User", on_delete=models.CASCADE, related_name="posts")
    body = models.CharField(max_length=1024)
    like_counter = models.IntegerField(default=0)
    comments = models.ManyToManyField("Comment", related_name="comment", blank=True)
    timestamp = models.DateTimeField( null=True, blank=True)

    def serialize(self):
        return {
            "author": self.author.username,
            "body": self.body,
            "comments": [comment.body for comment in self.comments.all()],
            "timestamp": str(self.timestamp).replace(" ", ""),
            "day": self.timestamp.day,
            "month": self.timestamp.month,
            "year": self.timestamp.year
        }

class Like(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey("Post", on_delete=models.CASCADE)


class Comment(models.Model):
    body = models.TextField()
    author = models.ForeignKey("User", on_delete=models.CASCADE)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)

network/forms.py
from django import forms

class NewPostForm(forms.Form):
    body = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={
            'class' : 'form-control col-9 entry_content h-50',
            'rows':'3',
            'placeholder':'What are you thinking about?'
        }))
    

network/views.py
from django.contrib.auth import authenticate, login, logout, get_user
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import json
from pytz import utc
from .forms import NewPostForm
from pprint import pprint
from .models import User, Post, Like, Comment



def index(request):
    context = {}
    posts = Post.objects.all()
    posts = posts.order_by("-timestamp").all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    if page_number == None:
        page_number = 1
    page_obj = paginator.page(page_number)
    context["page"] = page_obj
    context["newPostForm"] = NewPostForm
    if get_user(request).is_authenticated:
        context["liked_posts"] = User.objects.get(username=get_user(request)).liked_posts.all()
    return render(request, "network/index.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


@login_required
def add_post(request):
    print("got here")
    print(datetime.now())
    if request.method == "POST":
        form = NewPostForm(request.POST)
        if form.is_valid():
            body = form.cleaned_data["body"]
            post = Post.objects.get(id=request.POST.get("id"))
            if post:
                post.body = body
            else:
                post = Post(
                    author = get_user(request),
                    body=body,
                    timestamp=utc.localize(datetime.utcnow())
                )
            post.save() 
    return HttpResponseRedirect(reverse("network:index"))
    

# @login_required
# def profile(request, username):
#     user = User.objects.get(username=username)
#     to_follow = None
#     if user != get_user(request):
#         to_follow = True if len(user.followers.filter(username=get_user(request))) == 0 else False
    
#     user = user.serialize()
#     user["toFollow"] = to_follow
#     return JsonResponse(user)   


@login_required
def posts(request):
    posts = Post.objects.all()
    posts = posts.order_by("-timestamp").all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return JsonResponse([post.serialize() for post in page_obj], safe=False)


@login_required
def user_posts(request, username):
    context = {}
    user = User.objects.get(username=username)
    to_follow = None
    if user != get_user(request):
        to_follow = "Follow" if len(user.followers.filter(username=get_user(request))) == 0 else "Unfollow"
    else:
        to_follow = None
    context["user_details"] = user.serialize()
    context["to_follow"] = to_follow

    posts = Post.objects.all().filter(author=user)
    posts = posts.order_by("-timestamp").all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    if page_number == None:
        page_number = 1
    page_obj = paginator.page(page_number)
    context["page"] = page_obj
    context["username"] = user.username
    return render(request, "network/profile.html", context)


@login_required
def follow_user(request, user_to_follow):
    if request.method == "GET":
        return HttpResponse("POST request only!")
    current_user = User.objects.get(username=get_user(request))
    user_to_follow = User.objects.get(username=user_to_follow)
    try:
        current_user.following.get(username=user_to_follow)
        current_user.following.remove(user_to_follow)
        user_to_follow.followers.remove(current_user)
        print("its ok")
    except Exception:
        current_user.following.add(user_to_follow)
        user_to_follow.followers.add(current_user)
        
    return HttpResponseRedirect(reverse("network:profile", kwargs={'username':user_to_follow}))


@login_required
def following_view(request):
    user = get_user(request)
    following_users = user.following.all()
    following_posts = []
    context = {}
    for following_user in following_users:
        following_posts.extend(Post.objects.all().filter(author=following_user))

    # following_posts = [post.serialize() for post in following_posts]
    paginator = Paginator(following_posts, 10)
    page_number = request.GET.get('page')
    if page_number == None:
        page_number = 1
    page_obj = paginator.page(page_number)
    context["page"] = page_obj
    return render(request, "network/index.html", context)


@login_required
def like(request, post_id):
    context = {
        
    }
    post = Post.objects.get(id=post_id)
    user = get_user(request)
    if post in user.liked_posts.all():
        user.liked_posts.remove(post)
        post.like_counter -=1
        nextBtn = "Like"
    else:
        user.liked_posts.add(post)
        post.like_counter += 1
        nextBtn = "Unlike"

    post.save()
    user.save()

    return JsonResponse({
        "message":"Successfuly liked",
        "currentCounter":post.like_counter,
        "buttonContent":nextBtn
    })

network/templates/network/index.html
{% include "network/layout.html" %}

{% load static %}

{% block body %}
    <div>
        <div id="new-post">
            <!-- {% if user.is_authenticated %} -->
            <form id="new-post-form" method="POST" action="{% url 'network:add_post' %}">
            
                {% csrf_token %}
                {{newPostForm}}
                <input type="submit" id="submit" class="btn btn-primary mb-2">
                
            </form>
            <!-- {% endif %} -->
        </div>
        <div class="container" id="posts-view">
            <h3>News feed</h3>
            {% for post in page%}
                <div>
                    {% block post_block %}
                    {% include 'network/post.html' %}
                    {% endblock %}
                </div>
                <br>
            {% empty %}
                <p>Nothing here</p>
            {% endfor %}

        </div>

        

        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% if page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>          
    
    </div>
    
    
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <script src="{% static 'network/index.js' %}"></script>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong id="get-profile">{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="/" id="news-feed">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}" id="following">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:user_posts' user.username %}" id="profile">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/post.html
{% load static %}

{% block post_block %}
    <div>
        <a href="{% url 'network:profile' post.author %}"><h4>{{post.author}}</h4></a>
        <p>{{post.timestamp}}</p>
        <p id="post-body-{{post.id}}">{{post.body}}</p>


        {% if request.user == post.author %}
        <form method="POST" style="display: none;" class="" id="edit-form-{{post.id}}" action="{% url 'network:add_post' %}">
            {% csrf_token %}
            <textarea name="body" cols="40" rows="3" class="form-control col-9 entry_content h-50" required id="id_body">
            {{post.body}}
            </textarea>
            <input type="hidden" name="id" value="{{post.id}}">
            <input type="submit" class="btn btn-default" >
            <button type="button" class="btn btn-default" id="cancel-{{post.id}}">Cancel</button>
        </form>
        <button class="btn edit-btn" id="{{post.id}}">Edit</button>
        {% endif %}
        {% if user.is_authenticated %}

            {% if post in liked_posts %}
                <button class="btn unlike-btn" id="unlike-{{post.id}}">Unlike</button>

            {% else %}
                <button class="btn like-btn" id="like-{{post.id}}">Like</button>
            {% endif %}
        {% endif %}
        
        <p id="like-counter-{{post.id}}">Likes: {{post.like_counter}}</p>

        </div>
    <br>
{% endblock %}

network/templates/network/profile.html
{% include 'network/layout.html' %}

{% load static %}

{% block body %}

      <div class="container" id="posts-view">
        

        <nav class="navbar navbar-expand-lg navbar-light">
            <h3 class="navbar-brand">{{user.username}}'s profile</h3>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    Followers: {{user_details.noFollowers}}
                  </li>
                  <li class="nav-item">
                    Following: {{user_details.noFollowing}}
                  </li>
                </ul>
                {% if to_follow  %}
                    <div class="container" id="profile-view">
                        <form method="POST" action="{% url 'network:follow_user' user_details.username %}">
                            {% csrf_token %}
                            <input type="submit" value="{{to_follow}}"></input>
                        </form>
                    </div>
                {% endif %}

            </div>
        </nav>

        {% for post in page%}
            {% block post_block %}
            {% include 'network/post.html' %}
            {% endblock %}
        {% empty %}
            <p>Nothing here</p>
        {% endfor %}
        
          <!-- <script>
            $('#exampleModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var recipient = button.data('whatever') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title').text('New message to ' + recipient)
                modal.find('.modal-body input').val(recipient)
              })
            </script> -->
            
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% if page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav> 
        
    </div>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}